# Generated by Django 3.2.6 on 2021-08-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_recursos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursos',
            name='delay',
            field=models.CharField(default='0.3s', max_length=5, verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='icone',
            field=models.CharField(choices=[('lni-rocket', 'Foguete'), ('lni-laptop-phone', 'Gráficos'), ('lni-cog', 'Engrenagem'), ('lni-leaf', 'Folha'), ('lni-layers', 'Camadas'), ('lni-leaf', 'Folha')], max_length=16, verbose_name='Icone'),
        ),
    ]
